### ISSUE TITLE
ASReview - 80 sample coding 

### ISSUE THREAD

**Issue by nniiicc** [PugetSoundClinic-PIT/OSH_Review#1]
```[tasklist]
### Tasks
- [ ] Follow directions here to install https://asreview.nl/
- [ ] Create a new project (use Oracle mode as the setting) 
- [ ] Upload CSV  (stored in this repo) https://github.com/PugetSoundClinic-PIT/OSH_Review/blob/main/WoS_Records.csv
- [ ] Add "prior knowledge" by coding a few examples ... 
- [ ] The final screen will give you choices for how to set up the ML model - nothing to change here, just leave all options as the default setting 
- [ ] Screen 80 records... For irrelevant records add a note that helps us understand why the record is not relevant...  H (hardware), C (conceptual) or R (review)
- [ ] When you're finished export your project as a CSV and upload to this repository - we can compare our coding / progress and discuss next steps
```
