### ISSUE TITLE
Steps to completion - Scoping review 

### ISSUE THREAD

**Issue by thin-lizard** [PugetSoundClinic-PIT/OSH_Review#16]
**By Wed 10/09**
- [x] NW will review analysis part of [protocol](https://docs.google.com/document/d/1ts-VyCGtjB9pwRIShM0HZiSFL5SV-QWaEFAQuvqn-SY/edit) (https://github.com/PugetSoundClinic-PIT/OSH_Review/issues/15) - @nniiicc 
- [x] #21
- [x] https://github.com/PugetSoundClinic-PIT/OSH_Review/issues/17 
- [x] Check & share JOSH criteria - @lindseysschwartz - see https://github.com/PugetSoundClinic-PIT/OSH_Review/issues/19
- [x] **Assign remaining sections of paper (see below)**

**By Friday 10/11**
- [x] Finish descriptive analysis https://github.com/PugetSoundClinic-PIT/OSH_Review/issues/18

**By Wed 10/16**
- [ ] Draft [the paper](https://docs.google.com/document/d/1I_qxMUAmuoM6wEvnNB3V189bKL2A0mZ_rw2qgxD4x-M/edit#heading=h.e0do1lazmb7j)
	- [ ] Abstract - @nniiicc 
	- [ ] Introduction - @nniiicc 
	- ~~[ ] Background - (@sarah114tran and @lindseysschwartz)~~
	- [x] Methods - @lindseysschwartz 
	- [x] Results - @sarah114tran 

**By Friday 10/18**
- [x] #20

**By Thurs 10/31**
- [ ] Draft discussion section 
     - [x] RQs 1 & 2 - @lindseysschwartz 
     - [ ] RQ 3 -  @nniiicc 
     - [x] Future work - @sarah114tran 
     - [x] Conclusion - @lindseysschwartz 

**By Monday 11/4
- [ ] Swap / peer review sections of [paper draft](https://docs.google.com/document/d/1I_qxMUAmuoM6wEvnNB3V189bKL2A0mZ_rw2qgxD4x-M/edit#heading=h.e0do1lazmb7j)
	- [ ] Abstract - @sarah114tran & @lindseysschwartz 
	- [ ] Introduction & Background - @sarah114tran & @lindseysschwartz 
	- [ ] Methods - @sarah114tran 
	- [ ] Results - @lindseysschwartz 
	- [ ] Discussion - @nniiicc 
	- [ ] Conclusion & Future Work - @nniiicc

**Comment by sarah114tran** [comment]
@nniiicc @lindseysschwartz 

The [OSH_LitCoding](https://docs.google.com/spreadsheets/d/1GGzE0qIDeKrOaxUrFpMTOaaNsXrHkODmvqBDLHI9rlM/edit?gid=1647973721#gid=1647973721) sheet has the set of 10 to be coded for method and data collection method

**Comment by nniiicc** [comment]
Happy to do abstract and introduction... 
Can you please link to the Protocol for me to review? (NW will review analysis part of protocol)

**Comment by sarah114tran** [comment]
Hello! I created a [Draft #2](https://docs.google.com/document/d/1ykMZS_0aRUk0D17yiJcKkTD_jFObDPQVO7g8iyYsGUw/edit?usp=sharing) of the OSH Review to see the areas that need to completed and peer reviewed. Feel free to continue making changes on the original [OSH_PaperDraft #1](https://docs.google.com/document/d/1I_qxMUAmuoM6wEvnNB3V189bKL2A0mZ_rw2qgxD4x-M/edit?usp=sharing), the new draft is mainly to see all of the parts together. 

These are the next steps to complete the OSH Review: 

@sarah114tran tasks: 
- [x] Write contributions and paper outline paragraph 
- [x] Code extra papers in [this spreadsheet](https://docs.google.com/spreadsheets/d/13m8h3-o3fkBPnuUukl7dABeAeLJD3Mw_hlYoykE8Sj4/edit?gid=1856185636#gid=1856185636)
- [x] Update the final corpus of papers and update the percentages in the paper (quick reminder from LS to include the 'counts' (n=  ) with the percentages as well!! 😰 😰 )
- [x] Any loose ends/areas that need to be filled in 
- [x] Peer review conclusion 
- [ ] Add in citations 

@nniiicc tasks: 
- [ ] Peer review the introduction paragraph 
- [ ] Write the introduction section -- there is some preliminary information for the background, but it does not have to be used! 
- [ ] Answer research question 3 

@lindseysschwartz tasks: 
- [x] Code extra papers in [this spreadsheet](https://docs.google.com/spreadsheets/d/13m8h3-o3fkBPnuUukl7dABeAeLJD3Mw_hlYoykE8Sj4/edit?gid=1856185636#gid=1856185636)
- [x] Peer review disc. & future resaerch & conclusion section 
- [x] Citations
- [ ] Any loose ends/areas that need to be filled in 

Not sure what everyones schedule is looking like, but lets tentatively aim to complete these tasks by Tuesday 10/12!

**Comment by thin-lizard** [comment]
@sarah114tran happy to coordinate on loose ends!

**Comment by sarah114tran** [comment]
@nniiicc A background section is need based on the journal open hardware submission requirements. I think it would be best to expand on the introduction section instead!
