### ISSUE TITLE
Next Steps: 08.21.2024

### ISSUE THREAD

**Issue by nniiicc** [PugetSoundClinic-PIT/OSH_Review#5]
```[tasklist]
### Tasks
- [x] @nniiicc Decide on which databases we should search
- [x] @nniiicc - share search query with Sarah to execute searches
- [x] @sarah114tran - do searches and deduplicate results
- [x] @sarah114tran - add new publications to ASReview dataset
- [x] @sarah114tran - read https://dl.acm.org/doi/pdf/10.1109/FLOSS.2009.5071355 for criteria on inclusion / exclusion, and how they define "empirical"
```

**Comment by sarah114tran** [comment]
Hi @nniiicc! 
1. Read over the paper and the authors sadly do not include their criteria on inclusion/exclusion or their definition for empirical. I did find this paper by the same authors - https://dl.ifip.org/db/conf/oss/oss2009/StolB09.pdf , which might be of interest to us because they set out to access the quality of empirical research in OSS. 
2. Here are the listed RQs:
- What kind of empirical studies have been conducted in OSS-related research?
- What is the quality of reporting empirical studies in OSS-related research?
- How can the quality of reporting empirical research of OSS be improved?

**Comment by sarah114tran** [comment]
Adding onto the previous comment...
1. https://www.webofscience.com/wos/woscc/full-record/WOS:000282905700001 - this paper in section 3.1.5 provides a good definition of empirical research that may be helpful for us
